baseUrl: https://lecomtoisduweb.com
collections:
    posts:
        output: true
        permalink: /blog/:year/:month/:day/:title.html
exclude: [
    'CNAME',
    'Gemfile.lock',
    'Gemfile',
    'README.md',
]
highlighter: rouge
host: 0.0.0.0
incremental: true
kramdown:
    input: GFM
    hard_wrap: false
markdown: kramdown
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
